version: '3.4'

services:
  booking_api:
    image: booking-api:latest
    depends_on:
      - "booking_db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:80"     
    environment:
      DB_CONNECTION_STRING: "host=booking_db;port=5432;database=booking_dev;username=bookinguser;password=bookingpwd"
  
  booking_db:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - booking_db_vol:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "bookinguser"
      POSTGRES_PASSWORD: "bookingpwd"
      POSTGRES_DB: "booking_dev"

volumes:
  booking_db_vol:
         
    
     